#!/usr/bin/env python3
import os
import sys

if __name__ == "__main__":
    MODULE_PATH = os.path.dirname(os.path.realpath(__file__))
    REPO_PATH = os.path.dirname(MODULE_PATH)
    sys.path.insert(0, REPO_PATH)

from mdnscheckup.mdns_cli import main

if __name__ == "__main__":
    sys.exit(main())